// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PictureSorter.Data.Context;

#nullable disable

namespace PictureSorter.Data.Migrations
{
    [DbContext(typeof(PictureSorterDbContext))]
    partial class PictureSorterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PictureSorter.Data.Entities.SortMemoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("FileSignature")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath")
                        .HasDatabaseName("IX_SortMemory_Folder");

                    b.HasIndex("FolderPath", "FileSignature", "CategoryName")
                        .IsUnique()
                        .HasDatabaseName("IX_SortMemory_Folder_Signature_Category");

                    b.ToTable("SortMemory", (string)null);
                });

            modelBuilder.Entity("PictureSorter.Data.Entities.SortRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUndone")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique()
                        .HasDatabaseName("IX_SortRun_RunId");

                    b.HasIndex("IsUndone", "StartedAtUtc")
                        .HasDatabaseName("IX_SortRun_IsUndone_StartedAtUtc");

                    b.ToTable("SortRun", (string)null);
                });

            modelBuilder.Entity("PictureSorter.Data.Entities.SortRunItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileSignature")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SortRunId")
                        .HasDatabaseName("IX_SortRunItem_SortRunId");

                    b.ToTable("SortRunItem", (string)null);
                });

            modelBuilder.Entity("PictureSorter.Data.Entities.SortRunItemEntity", b =>
                {
                    b.HasOne("PictureSorter.Data.Entities.SortRunEntity", "SortRun")
                        .WithMany("Items")
                        .HasForeignKey("SortRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SortRun");
                });

            modelBuilder.Entity("PictureSorter.Data.Entities.SortRunEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
